/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 animazione.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/animazione.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="NurbsPath" position={[-19.127, 33.611, -9.205]} rotation={[0, 0, -Math.PI / 2]} />
        <group name="NurbsPath001" position={[-32.327, 36.746, -15.052]} rotation={[0, 0, -Math.PI / 2]} />
        <group name="NurbsPath002" position={[-47.85, 22.617, 5.73]} rotation={[0, 0, -Math.PI / 2]} />
        <group name="NurbsPath003" position={[7.337, 40.02, -6.811]} rotation={[0, 0, -1.554]} />
        <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={5.223} position={[17.279, 56.133, -173.73]} rotation={[-2.915, 0.017, 3.138]} />
        <mesh name="Cloud_4007" geometry={nodes.Cloud_4007.geometry} material={nodes.Cloud_4007.material} position={[-15.965, 91.028, -9.205]} rotation={[-1.536, 0.013, -2.011]} scale={[0.944, 1.029, 1.361]} />
        <mesh name="Cube069" geometry={nodes.Cube069.geometry} material={nodes.Cube069.material} position={[6.829, 70.588, -6.811]} rotation={[0, 0, 0.017]} scale={[0.152, 0.342, 0.277]} />
        <mesh name="Cube088" geometry={nodes.Cube088.geometry} material={nodes.Cube088.material} position={[4.052, 210.376, 5.73]} rotation={[-2.203, 1.553, -0.925]} />
        <mesh name="mouse" geometry={nodes.mouse.geometry} material={nodes.mouse.material} position={[-7.056, 55.964, -29.119]} rotation={[Math.PI, -1.373, Math.PI]} scale={[1.509, 0.854, 1.106]} />
        <mesh name="Banana_Cube038" geometry={nodes.Banana_Cube038.geometry} material={materials.Yellow} position={[-31.779, 96.238, -15.052]} rotation={[-0.175, 0.018, 0.103]} scale={-14.477} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[34.749, 86.35, -6.878]} rotation={[0, 0, 0.108]} scale={0.613} />
      </group>
    </group>
  )
}

useGLTF.preload('/animazione.glb')
